[auth]
cookie_secret = "xxxxxxxxxxxxxxxxxxxxxxxx"
cookie_name = "streamlit_app"
cookie_expiry_days = 30
preauthorized = []

[connections.supabase]
SUPABASE_URL = "https://fwubuqwsuvkdzqmoyxxz.supabase.co"
SUPABASE_KEY = "sb_publishable__mkfeGz3uXdpAFTjvxTxbw_msg13nov"